services:
  web01:
    image: httpd
    container_name: web01
    volumes:
      - ./volumes/web1/:/usr/local/apache2/htdocs/
    ports:
      - 8081:80
  web02:
    image: httpd
    container_name: web02
    volumes:
      - ./volumes/web2/:/usr/local/apache2/htdocs/
    ports:
      - 8082:80
  lb:
    image: nginx
    container_name: lb 
    volumes:
      - ./volumes/lb/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web01
      - web02
